#!/bin/bash

# Get current states at startup
SENSOR="sensor.btt_sensors"
RESPONSE=$(wget --quiet --no-check-certificate --header="Authorization: Bearer ${BEARER}" --header="Content-Type: application/json" -qO - ${REST_API}/${SENSOR})
ENTITIES=$(echo "$RESPONSE" | jq -r '.attributes' | jq 'to_entries')
INDEX=1

# Set current states at startup using combo sensor attributes
echo "$ENTITIES" | jq -c -r '.[]' | while read item; do
  entity=$(jq -r '.key' <<<"$item")
  state=$(jq -r '.value' <<<"$item")

  if [[ $INDEX < 6 ]]; then
    echo "$INDEX = $entity : $state"
    ./controllers/btt "$INDEX" "$state"
  fi

  ((INDEX++))
done
